# Site settings
title: ICML Visualization Workshop
email: bjiang@berkeley.edu
description: > # this means to ignore newlines until "baseurl:"
  Built with Jekyll
baseurl: "/ICMLViz" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

kramdown:
  input: GFM
